GLCD Library: Controllers
Controllers
Controller specific functions.
Functions
void glcd_command (uint8_t c)
Send command byte to LCD.
void glcd_data (uint8_t c)
Send data byte to LCD.
void glcd_power_down (void)
Power down the device.
void glcd_power_up (void)
Power up the device.
void glcd_set_contrast (uint8_t val)
Set contrast.
void glcd_set_x_address (uint8_t x)
Set X address of RAM (column).
void glcd_set_y_address (uint8_t y)
Set Y address of RAM (select bank).
void glcd_write (void)
Update the display within the specified bounding box.
Detailed Description
Controller specific functions.
Currently only the following controllers are supported:
PCD8544 (Nokia 5110 LCD) SPI interface
ST7565R with SPI interface
The C and header files defining these functions are stored in the subdirectory:
devices/
Function Documentation
void glcd_command (uint8_t c)
Send command byte to LCD.
Parameters
c Command byte to be written to LCD
void glcd_data (uint8_t c)
Send data byte to LCD.
Parameters
c Data byte to be written to LCD
void glcd_power_down (void)
Power down the device.
void glcd_power_up (void)
Power up the device.
void glcd_set_contrast (uint8_t val)
Set contrast.
Parameters
val Value from 0 to 127. This should be experimentally determined. Supported by PCD8544 only.
void glcd_set_x_address (uint8_t x)
Set X address of RAM (column).
Device must be under basic instruction set mode before using this.
Parameters
x X address of RAM (0 <= X <= GLCD_LCD_WIDTH-1)
See Also
GLCD_LCD_WIDTH
void glcd_set_y_address (uint8_t y)
Set Y address of RAM (select bank).
for PCD8544, device must be under basic instruction set mode before using this.
Parameters
y page address of RAM (0 <= Y < GLCD_LCD_HEIGHT/8)
See Also
GLCD_LCD_HEIGHT
GLCD_NUMBER_OF_BANKS
Note
Update: y is actually bank number, not pixel number!
void glcd_write (void)
Update the display within the specified bounding box.
This physically writes data to the device's RAM.
Referenced by glcd_clear(), glcd_draw_bitmap(), glcd_scrolling_bar_graph(), glcd_test_bitmap_128x64(), glcd_test_circles(), glcd_test_counter_and_graph(), glcd_test_hello_world(), glcd_test_rectangles(), glcd_test_scrolling_graph(), glcd_test_text_up_down(), glcd_tiny_draw_string_ammend(), and glcd_tiny_draw_string_ammend_P().